// Code generated by "stringer -type=Color,Value -linecomment=true"; DO NOT EDIT.

package cards

import "strconv"

const _Color_name = "WildRedYellowGreenBlue"

var _Color_index = [...]uint8{0, 4, 7, 13, 18, 22}

func (i Color) String() string {
	if i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}

const _Value_name = "ZeroOneTwoThreeFourFiveSixSevenEightNineSkipReverseDraw TwoDraw FourChoose"

var _Value_index = [...]uint8{0, 4, 7, 10, 15, 19, 23, 26, 31, 36, 40, 44, 51, 59, 68, 74}

func (i Value) String() string {
	if i >= Value(len(_Value_index)-1) {
		return "Value(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Value_name[_Value_index[i]:_Value_index[i+1]]
}
